version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    groups:
      bun-security-updates:
        applies-to: security-updates
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    groups:
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - '*'
